enum {
	PI_LIBC_PUTS=0x0101,
    PI_LIBC_OPEN,
    PI_LIBC_CLOSE,
    PI_LIBC_WRITE,
    PI_LIBC_READ,
    PI_LIBC_CHDIR,
    PI_LIBC_GETCWD,
    PI_LIBC_SYSTEM,
    PI_LIBC_LSEEK,
    PI_LIBC_UNLINK,
    PI_LIBC_SYSEXIT,

	PI_LIBC_LAST_OPCODE,
};